services:
  backend:
    build:
      context: ./exp       # Spring projesi burada
      dockerfile: Dockerfile
    container_name: beeserver-backend
    restart: unless-stopped
    environment:
      # Mevcut PostgreSQL container'ın host portu: 5432
      # Host IP: 10.139.14.251 (veya localhost da iş görür)
      SPRING_DATASOURCE_URL: jdbc:postgresql://10.139.14.251:5432/taskdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password123

      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      APP_SECURITY_JWT_SECRET: "super-secret-key-change-this-please-1234567890"
      APP_SECURITY_JWT_EXPIRATION_MS: 86400000
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
