version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: appbee-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: appbee
      POSTGRES_USER: appbee
      POSTGRES_PASSWORD: appbee
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appbee-net
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appbee-backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://10.139.14.251:5432/taskdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password123

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APP_SECURITY_JWT_SECRET: "super-secret-key-change-this-please-1234567890"
      APP_SECURITY_JWT_EXPIRATION_MS: 86400000
      SERVER_PORT: 8080

    ports:
      - "8080:8080"
    networks:
      - appbee-net

volumes:
  pgdata:

networks:
  appbee-net:
    driver: bridge
